version: '3.7'

services:
  app:
    image: discord-bot
    build: .
    container_name: discord-bot
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "80:80"
    volumes:
      - ./src/bot.php:/app/bot.php
      - ./99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini